## SPARSE MATRIX

### CSR

In [28]:
import scipy
import numpy as np

In [27]:
# TEST CASE - 1
docs = [["hello", "world", "hello"], ["goodbye", "cruel", "world"]]
indptr = [0]
indices = []
data = []
vocabulary = {}
for d in docs:
    for term in d:
        index = vocabulary.setdefault(term, len(vocabulary))
        indices.append(index)
        data.append(1)
    indptr.append(len(indices))
csr_mat = scipy.sparse.csr_matrix((data, indices, indptr), dtype=int)
print("indptr ", csr_mat.indptr)
print("column ", csr_mat.indices)
print("shape ", csr_mat.shape)
print("data ", csr_mat.data)
print("csr")
print(csr_mat)
print("array")
print(csr_mat.toarray())

indptr  [0 3 6]
column  [0 1 0 2 3 1]
shape  (2, 4)
data  [1 1 1 1 1 1]
csr
  (0, 0)	1
  (0, 1)	1
  (0, 0)	1
  (1, 2)	1
  (1, 3)	1
  (1, 1)	1
array
[[2 1 0 0]
 [0 1 1 1]]


In [32]:
# TEST CASE - 2
csr_mat = scipy.sparse.csr_matrix([[1, 2, 0], [0, 0, 3], [4, 0, 5]])
print("indptr ", csr_mat.indptr)
print("column ", csr_mat.indices)
print("shape ", csr_mat.shape)
print("data ", csr_mat.data)
print("csr")
print(csr_mat)
print("array")
print(csr_mat.toarray())

indptr  [0 2 3 5]
column  [0 1 2 0 2]
shape  (3, 3)
data  [1 2 3 4 5]
csr
  (0, 0)	1
  (0, 1)	2
  (1, 2)	3
  (2, 0)	4
  (2, 2)	5
array
[[1 2 0]
 [0 0 3]
 [4 0 5]]


## TF-IDF

In [2]:
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd
corpus = ['This is the first document.', 'This document is the second document.', 'And this is the third one.', 'Is this the first document?']
vectorizer = TfidfVectorizer(stop_words="english")
X = vectorizer.fit(corpus).transform(corpus)
# X = vectorizer.fit_transform(corpus)
df = pd.DataFrame(X.toarray(), columns = vectorizer.get_feature_names_out())
df

document    second
0  1.000000  0.000000
1  0.787223  0.616668
2  0.000000  0.000000
3  1.000000  0.000000

In [7]:
print(vectorizer.get_feature_names_out())
print(X.indptr)
print(X.data)
print(X.indices)
print(X.shape)
print(X)
print(type(X))
print(vectorizer.idf_)

['document' 'second']
[0 1 3 3 4]
[1.         0.61666846 0.78722298 1.        ]
[0 1 0 0]
(4, 2)
  (0, 0)	1.0
  (1, 1)	0.6166684570284895
  (1, 0)	0.78722297610404
  (3, 0)	1.0
<class 'scipy.sparse._csr.csr_matrix'>
[1.22314355 1.91629073]


## MIXED TESTS

In [8]:
import math
tf = 1 / 1
n = 4 # number of documents
df_t = 3
idf = math.log((1 + n) / (1 + df_t)) + 1
print("tf ", tf)
print("idf ",idf)
tf*idf

tf  1.0
idf  1.2231435513142097


1.2231435513142097

In [12]:
1/1.22314 * 0.815429

0.6666685743250977